server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql:///dubbo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  registry:
    address: zookeeper://192.168.118.168:2181
  application:
    name: customer-serviceimpl
  protocol:
    port: -1
  consumer:
    check: false
